## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.

In [1]:
import numpy as np
import pandas as pd

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [2]:
np.__version__

'1.16.5'

2. Crear un arreglo 1D con enteros positivos aleatorios

In [2]:
array_1d = np.array(np.random.randint(low=1,high=50,size=10))
array_1d

array([ 4,  3, 47, 40, 48, 15, 17, 42, 35, 45])

In [10]:
array_1d.ndim

1

3. Crear un arreglo booleano

In [3]:
array_bool = array_1d >= 25
array_bool

array([False, False,  True,  True,  True, False, False,  True,  True,
        True])

4. Extraer los items que sean divisibles en 3.

In [4]:
div_tres = [div for div in array_1d if div % 3 == 0]
div_tres

[3, 48, 15, 42, 45]

In [5]:
array_1d

array([ 4,  3, 47, 40, 48, 15, 17, 42, 35, 45])

5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [6]:
array_bool3 = np.delete(array_bool,1)


array([[False,  True,  True],
       [ True, False, False],
       [ True,  True,  True]])

6. Obtén los items comunes entre dos arreglos

In [246]:
array_1 = np.array(np.random.randint(low = 1, high = 10, size = 15))
array_2 = np.array(np.random.randint(low = 1, high = 10, size = 15))

In [247]:
array_1,array_2

(array([5, 6, 5, 3, 9, 8, 2, 2, 7, 3, 8, 6, 7, 9, 8]),
 array([1, 1, 5, 8, 5, 4, 9, 8, 5, 5, 3, 3, 3, 2, 2]))

In [248]:
items_comunes = [comun for comun in array_1 if comun in array_2]
set(items_comunes)

{2, 3, 5, 8, 9}

7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [8]:
array_1d

array([ 4,  3, 47, 40, 48, 15, 17, 42, 35, 45])

In [11]:
prom = round(np.mean(array_1d))
prom

30.0

In [12]:
numeros = [n for n in array_1d if n == (prom+2) or n == prom-2]
numeros

[]

8. Muestra solo 3 decimales en un vector.

In [222]:
print(np.array([np.round(np.random.rand(4),3)]))

[[0.226 0.538 0.412 0.874]]


9. Crea una matriz de 3x3 con los valores del 0 a 8

In [53]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [31]:
a = np.array([1,2,0,0,4])
indices = []
for i in range(len(a)):
    if a[i] != 0:
        indices.append(i)
print(indices)

[0, 1, 4]


In [23]:
a[np.array([3, 1, 2 ])]

array([0, 2, 0])

11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [32]:
m = np.random.randint(50,size=30)
m

array([42, 37, 15, 15, 11, 49, 36, 36,  9, 10, 37, 32, 18, 37, 12, 19, 19,
       41, 40, 16, 31, 23,  7, 33,  3, 10, 24, 12, 17, 11])

In [33]:
m.sort()

In [34]:
m

array([ 3,  7,  9, 10, 10, 11, 11, 12, 12, 15, 15, 16, 17, 18, 19, 19, 23,
       24, 31, 32, 33, 36, 36, 37, 37, 37, 40, 41, 42, 49])

In [41]:
mediana = m[14]
media = np.mean(m)
print("La mediana es:",mediana,"","La media es: ",media)

La mediana es: 19  La media es:  23.4


12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [240]:
n = 6
m = 5
elementos = n*m
arreglo = np.zeros(elementos).reshape(n,m)
arreglo

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [241]:
arreglo.shape

(6, 5)

In [242]:
arreglo.size

30

In [243]:
arreglo[0,] = np.ones(m)
arreglo[-1,] = np.ones(m)
arreglo[:,0] = np.ones(n)
arreglo[:,-1] = np.ones(n)

In [244]:
arreglo

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`

In [43]:
0 * np.nan

nan

In [44]:
np.nan == np.nan

False

In [45]:
np.inf > np.nan

False

In [46]:
np.nan - np.nan

nan

In [47]:
np.nan in set([np.nan])

True

In [48]:
0.3 == 3 * 0.1

False

In [51]:
0.3 == (3*.1)

False


14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

In [53]:
identidad = np.eye(5,5)

In [62]:
identidad[0,1:] = np.arange(1,5,1)

In [63]:
identidad

array([[1., 1., 2., 3., 4.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
identidad[1,2:] = np.arange(1,4,1)

In [66]:
identidad[2,3:] = np.arange(1,3,1)

In [67]:
identidad[3,4:] = np.arange(1,2,1)

In [68]:
identidad

array([[1., 1., 2., 3., 4.],
       [0., 1., 1., 2., 3.],
       [0., 0., 1., 1., 2.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1.]])

15. Normaliza una matriz aleatoria de 5x5

In [69]:
matriz = np.random.random((5,5))
matriz

array([[0.78568948, 0.30767448, 0.00383698, 0.28922727, 0.4929386 ],
       [0.28652229, 0.71945037, 0.82390782, 0.39078345, 0.33005508],
       [0.60717842, 0.93772838, 0.68156055, 0.32889929, 0.55274179],
       [0.15591447, 0.19942262, 0.29902581, 0.72973779, 0.98609942],
       [0.84705158, 0.43805211, 0.76730293, 0.7946811 , 0.8961843 ]])

In [71]:
row_sums = matriz.sum(axis=1)
new_matrix = matriz / row_sums[:, np.newaxis]

In [72]:
new_matrix

array([[0.41806074, 0.16371177, 0.00204164, 0.15389612, 0.26228972],
       [0.11233001, 0.28205787, 0.32301003, 0.15320521, 0.12939688],
       [0.19535304, 0.30170388, 0.21928468, 0.10581976, 0.17783865],
       [0.06578114, 0.08413746, 0.12616058, 0.30788024, 0.41604058],
       [0.22628641, 0.11702385, 0.20498188, 0.21229585, 0.23941202]])

In [75]:
new_matrix.sum(axis=1)

array([1., 1., 1., 1., 1.])

# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [78]:
import pandas as pd
pd.__version__

'0.25.1'

Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [79]:
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

In [81]:
df = pd.DataFrame(data)

In [82]:
df.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [84]:
df.head()

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no

3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [85]:
df.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

4. Regresa las primeras 3 filas del DataFrame

In [86]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [87]:
df.columns = ["Animal","Edad","Visitas","Prioridad"]
df.head()

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no

6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [104]:
df_2 = pd.DataFrame()
df_2["Animal"] = df["Animal"]
df_2["Edad"] = df["Edad"]

In [105]:
df_2

Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0

7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [121]:
df[df["Visitas"] > 3]

Empty DataFrame
Columns: [Animal, Edad, Visitas, Prioridad]
Index: []

8. ¿Cuáles son las filas donde la edad es NaN?

In [131]:
df["Edad"].isna()

a    False
b    False
c    False
d     True
e    False
f    False
g    False
h     True
i    False
j    False
Name: Edad, dtype: bool

In [ ]:
#R: d y h

9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [154]:
a = df[df["Edad"] >= 2]
a

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
i    dog   7.0        2        no
j    dog   3.0        1        no

In [155]:
a[a["Edad"] <= 4]

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
f    cat   2.0        3        no
j    dog   3.0        1        no

In [156]:
"3 gatos y un perro"

'3 gatos y un perro'

10. ¿Cuál es el total de todas las visitas?

In [165]:
df["Visitas"].sum()

19

# ¿Y el 11?

12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [186]:
df

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no

In [184]:
df.groupby(["Animal"]).count()

Edad  Visitas  Prioridad
Animal                          
cat        3        4          4
dog        3        4          4
snake      2        2          2

In [ ]:
#R: 4 gatos, 4 perros, 2 serpientes
#Observación: Al aparecer NaN, no lo cuenta en Edad

13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [190]:
df_copy = df.copy()

In [200]:
df_copy = df_copy.replace("yes",True)

In [201]:
df_copy = df_copy.replace("no",False)

In [202]:
df_copy

Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False

14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [212]:
df_copy.sort_values(by = "Edad",ascending=False)

Animal  Edad  Visitas  Prioridad
i    dog   7.0        2      False
e    dog   5.0        2      False
g  snake   4.5        1      False
b    cat   3.0        3       True
j    dog   3.0        1      False
a    cat   2.5        1       True
f    cat   2.0        3      False
c  snake   0.5        2      False
d    dog   NaN        3       True
h    cat   NaN        1       True

In [213]:
df_copy.sort_values(by = "Visitas",ascending=
                   True)

Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
g  snake   4.5        1      False
h    cat   NaN        1       True
j    dog   3.0        1      False
c  snake   0.5        2      False
e    dog   5.0        2      False
i    dog   7.0        2      False
b    cat   3.0        3       True
d    dog   NaN        3       True
f    cat   2.0        3      False

In [204]:
df_copy

Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False

15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [215]:
df.groupby(["Animal"]).mean()

Edad  Visitas
Animal               
cat      2.5      2.0
dog      5.0      2.0
snake    2.5      1.5

# 3. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto